DATALOADER:
  TRAIN_X:
    SAMPLER: 'RandomDomainSampler'
    BATCH_SIZE: 256
  TRAIN_U:
    SAME_AS_X: False
    BATCH_SIZE: 64
  TEST:
    BATCH_SIZE: 256

OPTIM:
  NAME: 'sgd'
  LR: 0.05
  STEPSIZE: [30]
  MAX_EPOCH: 30
  LR_SCHEDULER: 'cosine'

TRAINER:
  FIXMATCH:
    STRONG_TRANSFORMS: ['random_flip', 'randaugment_fixmatch', 'normalize', 'cutout']

