DATALOADER:
  NUM_WORKERS: 4
  TRAIN_X:
    SAMPLER: 'RandomDomainSampler'
    BATCH_SIZE: 32
  TRAIN_U:
    SAME_AS_X: False
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 100

OPTIM:
  NAME: 'sgd'
  LR: 0.01 # this lr is for new layers
  STAGED_LR: True
  NEW_LAYERS: ('backbone.layer1_adap', 'backbone.layer_adap', 'backbone.layer4_adap', 'backbone.layer2_adap', 'backbone.layer3_adap', 'backbone.layer4_new', 'backbone.dist_net_conv')
  BASE_LR_MULT: 0.1 # LR*BASE_LR_MULT is the final lr for the pre-trained layers

  MAX_EPOCH: 100
  LR_SCHEDULER: 'cosine'

TRAINER:
  FIXMATCH:
     STRONG_TRANSFORMS: ['random_flip', 'randaugment_fixmatch', 'normalize', 'cutout']
     EMA_ALPHA: 0.999


